// web/svelte/src/routes/empty-template.svelte
<script>
  let library = 'Demo';
  let widgets = [
    'Accordion',
    'Alert',
    'AlertDialog',
    'Breadcrumbs',
    'Button',
    'Carousel',
    'Checkbox',
    'Combobox',
    'Dialog',
    'Disclosure',
    'Feed',
    'Link',
    'Listbox',
    'Menu',
    'MenuButton',
    'RadioGroup',
    'Slider',
    'MultiThumbSlider',
    'Spinbutton',
    'Table',
    'Tabs',
    'Toolbar',
    'Tooltip',
    'TreeView',
    'TreeGrid',
    'WindowSplitter',
  ];
</script>

<svelte:head>
  <title>About</title>
</svelte:head>

<div class="container">
  <h1>Framework - VueJS</h1>
  <h2>Library - {library}</h2>
  <div class="cards">
    {#each widgets as widget, index}
      <div class="card">
        <h4 class="cardTitle">
          {index + 1 + '. ' + widget}
        </h4>
        <div class="cardContent">
          <!-- <slot :name="widget.toLowerCase()"></slot> -->
          not available
        </div>
      </div>
    {/each}
  </div>
</div>

<style scoped>
  .container {
    margin: 0 auto;
    width: '100%';
    max-width: 1200px;
    min-height: 100vh;
    padding: 0 1rem;
    height: 100vh;
  }

  .cards {
    margin-top: 50px;
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
  }

  .card {
    border: 1px solid #a0a0a0;
    display: flex;
    position: relative;
    min-height: 100px;
    width: 48%;
    margin-bottom: 50px;
    padding: 50px 10px 20px;
  }

  .cardTitle {
    border-right: 1px solid #a0a0a0;
    border-bottom: 1px solid #a0a0a0;
    position: absolute;
    top: 0;
    left: 0;
    padding: 5px 10px;
    margin: 0;
  }

  .cardContent {
    flex: 1;
  }
</style>

// web/angular/src/app/empty-template/empty-template.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-empty-template',
  templateUrl: './empty-template.component.html',
  styleUrls: ['../widget-template/widget-template.css'],
})
export class EmptyTemplateComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<div class="widget-container">
  <h1>Framework - AngularJS</h1>
  <h2>Library - Demo</h2>

  <div class="widget-cards">
    <div class="widget-card">
      <div class="widget-cardTitle">1. Accordion</div>
      <div class="widget-cardContent">
        <div class="widget-cardContent">not available</div>
      </div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">2. Alert</div>
      <div class="widget-cardContent">
        <div class="widget-cardContent">not available</div>
      </div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">3. Alert Dialog</div>
      <div class="widget-cardContent">
        <div class="widget-cardContent">not available</div>
      </div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">4. Breadcrumbs</div>
      <div class="widget-cardContent">not available</div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">5. Button</div>
      <div class="widget-cardContent">not available</div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">6. Carousel</div>
      <div class="widget-cardContent">
        <div class="widget-cardContent">not available</div>
      </div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">7. Checkbox</div>
      <div class="widget-cardContent">
        <h5>in the form of buttons</h5>
        <div class="widget-cardContent">not available</div>
      </div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">8. Combobox</div>
      <div class="widget-cardContent">
        <div class="widget-cardContent">not available</div>
      </div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">9. Dialog</div>
      <div class="widget-cardContent">
        <div class="widget-cardContent">not available</div>
      </div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">10. Disclosure</div>
      <div class="widget-cardContent">
        <div class="widget-cardContent">not available</div>
      </div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">11. Feed</div>
      <div class="widget-cardContent">not available</div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">12. Link</div>
      <div class="widget-cardContent">not available</div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">13. Listbox</div>
      <div class="widget-cardContent">not available</div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">14. Menu</div>
      <div class="widget-cardContent">not available</div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">15. Menu Button</div>
      <div class="widget-cardContent">not available</div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">16. Radio Group</div>
      <div class="widget-cardContent">
        <h5>in the form of buttons</h5>
        <div class="widget-cardContent">not available</div>
      </div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">17. Slider</div>
      <div class="widget-cardContent">not available</div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">18. Multi Thumb Slider</div>
      <div class="widget-cardContent">not available</div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">19. Spinbutton</div>
      <div class="widget-cardContent">not available</div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">20. Table</div>
      <div class="widget-cardContent">not available</div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">21. Tabs</div>
      <div class="widget-cardContent">not available</div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">22. Toolbar</div>
      <div class="widget-cardContent">not available</div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">23. Tooltip</div>
      <div class="widget-cardContent">not available</div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">24. Tree View</div>
      <div class="widget-cardContent">not available</div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">25. Treegrid</div>
      <div class="widget-cardContent">not available</div>
    </div>

    <div class="widget-card">
      <div class="widget-cardTitle">26. Window Splitter</div>
      <div class="widget-cardContent">not available</div>
    </div>
  </div>
</div>
