// web/angular/src/app/ng-bootstrap/carousel-widget/carousel-widget.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-carousel-widget',
  template: `
    <ngb-carousel *ngIf="images">
      <ng-template ngbSlide>
        <div class="picsum-img-wrapper">
          <img [src]="images[0]" alt="Random first slide" />
        </div>
        <div class="carousel-caption">
          <h3>First slide label</h3>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </div>
      </ng-template>
      <ng-template ngbSlide>
        <div class="picsum-img-wrapper">
          <img [src]="images[1]" alt="Random second slide" />
        </div>
        <div class="carousel-caption">
          <h3>Second slide label</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </ng-template>
      <ng-template ngbSlide>
        <div class="picsum-img-wrapper">
          <img [src]="images[2]" alt="Random 3rd slide" />
        </div>
        <div class="carousel-caption">
          <h3>Second slide label</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </ng-template>
    </ngb-carousel>
  `,
})
export class CarouselWidgetComponent implements OnInit {
  images = [944, 944, 944].map((n) => `https://picsum.photos/id/${n}/550/300`);

  constructor() {}

  ngOnInit(): void {}
}

// web/vue/components/Bootstrap/CarouselWidget.vue
<template>
  <div>
    <BCarousel
      id="carousel-1"
      v-model="slide"
      :interval="4000"
      controls
      indicators
      background="#ababab"
      img-width="1024"
      img-height="480"
      style="text-shadow: 1px 1px 2px #333;"
      @sliding-start="onSlideStart"
      @sliding-end="onSlideEnd"
    >
      <!-- Text slides with image -->
      <BCarouselSlide
        caption="First slide"
        text="Nulla vitae elit libero, a pharetra augue mollis interdum."
        img-src="https://picsum.photos/1024/480/?image=52"
      ></BCarouselSlide>

      <!-- Slides with custom text -->
      <BCarouselSlide img-src="https://picsum.photos/1024/480/?image=54">
        <h1>Hello world!</h1>
      </BCarouselSlide>

      <!-- Slides with image only -->
      <BCarouselSlide
        img-src="https://picsum.photos/1024/480/?image=58"
      ></BCarouselSlide>

      <!-- Slides with img slot -->
      <!-- Note the classes .d-block and .img-fluid to prevent browser default image alignment -->
      <BCarouselSlide>
        <template #img>
          <img
            class="d-block img-fluid w-100"
            width="1024"
            height="480"
            src="https://picsum.photos/1024/480/?image=55"
            alt="image slot"
          />
        </template>
      </BCarouselSlide>

      <!-- Slide with blank fluid image to maintain slide aspect ratio -->
      <BCarouselSlide caption="Blank Image" img-blank img-alt="Blank image">
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse
          eros felis, tincidunt a tincidunt eget, convallis vel est. Ut
          pellentesque ut lacus vel interdum.
        </p>
      </BCarouselSlide>
    </BCarousel>
  </div>
</template>

<script>
import { BCarouselSlide, BCarousel } from 'bootstrap-vue';

export default {
  components: { BCarouselSlide, BCarousel },
  data() {
    return {
      slide: 0,
      sliding: null
    };
  },
  methods: {
    onSlideStart(slide) {
      this.sliding = true;
    },
    onSlideEnd(slide) {
      this.sliding = false;
    }
  }
};
</script>
